<?php
// $Id$
/**
 * @file
 * This file holds the main Drupal hook functions 
 * and private functions for the jquery_colorpicker_cck module.
 *
 * @ingroup CCK
 */

/**
 * Implementation of hook_theme().
 */
function jquery_colorpicker_cck_theme() {
  return array(
    'jquery_colorpicker_cck' => array('arguments' => array('element' => NULL)),
    'jquery_colorpicker_cck_formatter_default' => array('arguments' => array('element' => NULL)),
    'jquery_colorpicker_cck_formatter_markup' => array('arguments' => array('element' => NULL)),
  );
}

/**
 * Implementation of hook_field_settings().
 */
function jquery_colorpicker_cck_field_settings($op, $field) {
  switch ($op) {
    case 'database columns':
      return array('value' => array('type' => 'varchar', 'length' => 64, 'not null' => FALSE, 'sortable' => TRUE));
    case 'views data':
      $allowed_values = content_allowed_values($field);
      break;
  }
}

/**
 * Implementation of hook_cck_widget_info()
 */
function jquery_colorpicker_cck_widget_info() {
  return array(
    'jquery_colorpicker_cck' => array(
      'label' => t('jQuery Colorpicker'),
      'field types' => array('colorpicker_cck_textfield'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}

/**
 * Implementation of FAPI hook_elements().
 *
 * Any FAPI callbacks needed for individual widgets can be declared here,
 * and the element will be passed to those callbacks for processing.
 *
 * Drupal will automatically theme the element using a theme with
 * the same name as the hook_elements key.
 *
 * Includes a regex to check for valid values as an additional parameter
 * the validator can use. The regex can be overridden if necessary.
 */
function jquery_colorpicker_cck_elements() {
  return array(
    'jquery_colorpicker_cck' => array(
      '#input' => TRUE,
  	  '#barco' => 'rojo',
      '#columns' => array('value'),
      '#delta' => 0,
      '#process' => array('jquery_colorpicker_cck_process'),
    ),
  );
}

/**
 * Process an individual element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function jquery_colorpicker_cck_process($element, $edit, $form_state, $form) {
  $field_name = $element['#field_name'];
  $field = $form['#field_info'][$field_name];
  $field_key = $element['#columns'][0];
  
  $value = isset($element['#value'][$field_key]) ? substr($element['#value'][$field_key],-6) : (isset($field['widget']['default_value'][0]['value']) ? substr($field['widget']['default_value'][0]['value'],1) : 'FFFFFF');

  $element['value'] = array(
    '#type' => 'colorpicker',
    '#default_value' => $value,
    '#title' => $element['#title'],
    '#description' => $element['#description'],
    '#required' => $element['#required'],
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );

  // Make sure we don't wipe out element validation added elsewhere.
  if (empty($element['#element_validate'])) {
    $element['#element_validate'] = array('jquery_colorpicker_cck_validate');
  }
  if (!empty($field['prefix'])) {
    $prefixes = explode('|', $field['prefix']);
    $element[$field_key]['#field_prefix'] = array_pop($prefixes);
  }
  if (!empty($field['suffix'])) {
    $suffixes = explode('|', $field['suffix']);
    $element[$field_key]['#field_suffix'] = array_pop($suffixes);
  }

  // Used so that hook_field('validate') knows where to flag an error.
  $element['_error_element'] = array(
    '#type' => 'value',
    '#value' => implode('][', array_merge($element['#parents'], array($field_key))),
  );

  if(isset($edit)) {
    // Next we decide what background to use to render the element. In order to ensure the background exists, we create an array of
    // the two possibilities, that we will use to compare the value submitted in the Form API definition
    $backgrounds = array('select.png', 'select2.png');
    // Now we check to see if the value in the Form API definition is valid. If it is, we use it, if it's not, we use a default value
    $background = (in_array($element['#jquery_colorpicker_background'], $backgrounds)) ? $element['#jquery_colorpicker_background'] : 'select.png';
    // Since we know the background, we can then get the URL of it to pass to the javascript function
    $background_url = base_path() . $path .'colorpicker/images/' . $background;
    // next we determine what the default value for the form element is. This will also be passed to the javascript function.
    if(isset($element['#value']['value'])) {
      $default_color = '#' . $element['#value']['value'];
    } else {
      $default_color = strtolower("#".$default_value);
    }
    // Finally we build an array of all the settings to be used by the javascript function
    $settings = array('ids' => array($element['#id'].'-value'), 'backgrounds' => array($background_url), 'backgroundColors' => array($default_color), $element['#id'] . '-defaultColor' => $default_color);

    // And we pass the settings in a namespace to the Javascript
    drupal_add_js(array('jqueryColorpicker' => $settings), 'setting');
  }

  return $element;
}

/**
 * Implementation of hook_widget().
 *
 * Attach a single form element to the form. It will be built out and
 * validated in the callback(s) listed in hook_elements. We build it
 * out in the callbacks rather than here in hook_widget so it can be
 * plugged into any module that can provide it with valid
 * $field information.
 *
 * Content module will set the weight, field name and delta values
 * for each form element. This is a change from earlier CCK versions
 * where the widget managed its own multiple values.
 *
 * If there are multiple values for this field, the content module will
 * call this function as many times as needed.
 *
 * @param $form
 * the entire form array, $form['#node'] holds node information
 * @param $form_state
 * the form_state, $form_state['values'] holds the form values.
 * @param $field
 * the field array
 * @param $delta
 * the order of this item in the array of subelements (0, 1, 2, etc)
 *
 * @return
 * the form item for a single element for this field
 */
function jquery_colorpicker_cck_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  $element = array(
    '#type' => $field['widget']['type'],
    '#default_value' => isset($items[$delta]) ? $items[$delta] : /*array('value' =>$field['widget']['default_value'][0]['value'])*/'',
  );
  return $element;
}

function jquery_colorpicker_cck_field_formatter_info() {
  return array(
    'default' => array(
      'label' => t('Default'),
      'field types' => array('colorpicker_cck_textfield'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'markup' => array(
      'label' => t('Markup'),
      'field types' => array('colorpicker_cck_textfield'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}


/**
 * Theme function for 'default' text field formatter.
 */
function theme_jquery_colorpicker_cck_formatter_default($element) {
  return '<div class="colorpicker '. check_plain($element['#item']['value']) .'">'. check_plain($element['#item']['value']) .'</div>';
}

/**
 * Theme function for 'plain' text field formatter.
 */
function theme_jquery_colorpicker_cck_formatter_markup($element) {
  return '<div class="colorpicker" style="background-color: '. $element['#item']['value'] .';">&nbsp;</div>';
}

/**
 * FAPI theme for an individual colorpicker_cck element.
 */
function theme_jquery_colorpicker_cck($element) {
  return $element['#children'];
}

function jquery_colorpicker_cck_validate($element, &$form_state) {
  if(isset($form_state['values'][$element['#field_name']])) {
    $form_state['values'][$element['#field_name']][$element['#delta']]['value'] = '#'. $form_state['values'][$element['#field_name']][$element['#delta']]['value'];
  } else {
    $form_state['values']['default_value_widget'][$element['#field_name']][0]['value'] = '#'. $form_state['values']['default_value_widget'][$element['#field_name']][0]['value'];
  }
}

/**
 * Implementation of hook_content_is_empty().
 *
 * If the colorpicker_cck module is installed,
 * the code from that module is used instead. However,
 * In the case where the this module is installed first,
 * then the colorpicker_cck module is installed after, this
 * function still needs to exist or else the site throws up
 * errors. As such, this module is not included in the module_exists()
 * code that follows this function.
 */
function jquery_colorpicker_cck_content_is_empty($item, $field) {
  if (empty($item['value']) && (string)$item['value'] !== '0') {
    return TRUE;
  }
  return FALSE;
}

/**
 * The following sets of functions are only included if the
 * colorpicker_cck module is not enabled. If the colorpicker_cck
 * module is enabled, these functions are ignored, and the
 * colorpicker_cck module's code is used.
 */
if(!module_exists('colorpicker_cck')) {
  /**
   * Implementation of hook_field_info()
   *
   * If the colorpicker_cck module is installed,
   * the code from that module is used instead.
   */
  function jquery_colorpicker_cck_field_info() {
    return array(
      'colorpicker_cck_textfield' => array(
        'label' => t('Colorpicker'),
        'description' => t('Store a jquery_colorpicker_cck in the database as an integer.'),
      ),
    );
  }

  /**
   * Implementation of hook_field()
   *
   * If the colorpicker_cck module is installed,
   * the code from that module is used instead.
   */
  function jquery_colorpicker_cck_field($op, &$node, $field, &$items, $teaser, $page) {
    if($op == 'validate') {
      if(is_array($items)) {
        foreach ($items as $delta => $item) {
          $error_element = isset($item['_error_element']) ? $item['_error_element'] : '';
           if ($item['value'] != '' && !preg_match('/^#(?:(?:[a-f\d]{3}){1,2})$/i', $item['value'])) {
            form_set_error($error_element, "'". check_plain($item['value']) ."'". t(' is not a valid hex color'));
          }
        }
      }
    }
    return $items;
  }

  /**
   * Implementation of hook_content_is_empty()
   *
   * This is a fix for the rare case where the colorpicker_cck module is installed first,
   * followed by an installation of the jquery_colorpicker_cck module, which is in turn
   * followed by an uninstallation of the colorpicker_cck module. In such a case, the
   * content module still looks for the function colorpicker_cck_content_is_empty(). Since
   * it doesn't exist anymore (because the colorpicker_cck module is uninstalled), it is
   * added here. This prevents the site from breaking.
   */
  if(!function_exists('colorpicker_cck_content_is_empty')) {
    function colorpicker_cck_content_is_empty() {
      if (empty($item['value']) && (string)$item['value'] !== '0') {
        return TRUE;
      }
      return FALSE;
    }
  }
}